import type { NamespaceBridgeSpec } from "../../../shared/bridge/spec";

const localSessionInvoke = [
  "addDirectories","archive","cancelQueuedMessage","checkGhAvailable","checkRemoteTrust","checkTrust","clearSession","commitAllChanges","commitWipForBranchSwitch","createAgent","createLocalPr","delete","disableAutoMerge","discardWorkingTree","enableAutoMerge","ensureBranchPushed","ensureSSHConnected","forkSession","generateLocalPrContent","getAgents","getAll","getCodeStats","getCommitDiff","getContextUsage","getDefaultEffort","getDefaultPermissionMode","getDetectedProjects","getDiffFileContent","getEffort","getGhIssue","getGitCommits","getGitDiff","getGitDiffStats","getGitInfo","getInstalledEditors","getLocalBranches","getMergeBase","getPermissionMode","getPlanForSession","getPrChecks","getPrDetails","getPrReviewComments","getPrStateForBranch","getSSHConfigs","getSSHGitInfo","getSSHSupportedCommands","getSession","getSessionsForScheduledTask","getShellPtyBuffer","getSupportedCommands","getTeleportReadiness","getTranscript","getTrustedSSHHosts","getUncommittedChanges","getWorkingTreeStatus","importCliSession","installGh","interrupt","isVSCodeInstalled","isWorkingTreeDirty","launchUltrareview","listGhIssues","listSSHDirectory","listSessionDirectory","logCliEvent","mergePr","openInEditor","openInVSCode","pickFileAtCwd","pickSessionFile","popBackgroundTaskSuggestion","readFileAtCwd","readSessionFile","readSessionImageAsDataUrl","releaseWorktree","replaceEnabledMcpTools","replaceRemoteMcpServers","resizePty","resizeShellPty","resolveSSHSettings","respondToSSHPassword","respondToToolPermission","reviewDiff","rewind","runBashCommand","saveTrust","searchSessions","sendMessage","sendSideChatMessage","setAutoFixEnabled","setAvailableCodeModels","setEffort","setFastMode","setFocusedSession","setMcpServers","setModel","setPermissionMode","setSSHConfigs","setTrustedSSHHosts","setVisibility","shareSession","start","startPty","startShellPty","startSideChat","stashWorkingTree","stop","stopPty","stopSessionSummary","stopShellPty","stopSideChat","stopTask","submitFeedback","summarizeSession","summarizeTranscript","teleportToCloud","testSSHConnection","unarchive","updatePrBody","updateSession","validateSSHPath","writePty","writeSessionFile","writeShellPty",
];

const localAgentModeSessionInvoke = [
  "abandonBridgeEnvironment","addFolderToSession","addTrustedFolder","archive","authorizeDirectMcpServer","delete","deleteBridgeAgentMemory","deleteBridgeSession","deleteLocalSkill","disconnectDirectMcpServer","getAll","getBridgeConsent","getDirectMcpServerStatuses","getLocalSkillFiles","getSession","getSessionsBridgeEnabled","getSessionsForScheduledTask","getSupportedCommands","getTranscript","getTranscriptFeedback","getTrustedFolders","interactiveAuth_$store$_getState","isFolderTrusted","kickBridgePoll","listLocalSkills","mcpCallTool","mcpListResources","mcpReadResource","noteCuWindowMentions","openOutputsDir","removeTrustedFolder","replaceEnabledMcpTools","replaceRemoteMcpServers","requestFolderTccAccess","resetBridge","resetBridgeSession","respondBridgePermissionPreflight","respondDirectoryServers","respondPluginSearch","respondSlashMenuSkills","respondToToolPermission","revealLocalSkill","revokeInteractiveAuth","rewind","saveLocalSkill","searchSessions","sendMessage","sessionsBridgeStatus_$store$_getState","setChromePermissionMode","setDraftSessionFolders","setFocusedSession","setLocalSkillEnabled","setMcpServers","setModel","setPermissionMode","setSessionsBridgeEnabled","shareSession","start","stop","submitTranscriptFeedback","syncSkills","triggerInteractiveAuth","updateSession",
];

export const webBridgeSpec: NamespaceBridgeSpec = {
  WindowControl: {
    invoke: ["resize", "focus", "close", "captureScreenshot", "setIncognitoMode", "setThemeMode"],
  },
  WindowState: {
    invoke: ["getFullscreen", "getVisibility", "getZoomFactor"],
    events: ["fullscreenChanged", "visibilityChanged", "zoomFactorChanged", "cuDockStateChanged"],
  },
  BrowserNavigation: {
    invoke: ["goBack", "goForward", "reportNavigationState", "requestMainMenuPopup", "navigationState_$store$_getState"],
    sync: ["navigationState_$store$_getStateSync"],
    events: ["navigationState_$store$_update"],
  },
  LocalSessions: {
    invoke: localSessionInvoke,
    events: ["onEvent", "onSSHPasswordRequired", "onToolPermissionRequest"],
  },
  LocalAgentModeSessions: {
    invoke: localAgentModeSessionInvoke,
    sync: ["interactiveAuth_$store$_getStateSync", "sessionsBridgeStatus_$store$_getStateSync"],
    events: ["interactiveAuth_$store$_update", "onBridgePermissionPreflight", "onCoworkFromMain", "onDirectMcpServerStatusesChanged", "onEvent", "onRemoteSessionStart", "onToolPermissionRequest", "sessionsBridgeStatus_$store$_update"],
  },
  CCDScheduledTasks: {
    invoke: [
      "getAllScheduledTasks",
      "getScheduledTaskFileContent",
      "updateScheduledTaskFileContent",
      "updateScheduledTaskStatus",
      "updateScheduledTask",
      "createScheduledTask",
      "removeApprovedPermission",
    ],
    events: ["onScheduledTaskEvent"],
  },
  CoworkScheduledTasks: {
    invoke: [
      "getAllScheduledTasks",
      "getScheduledTaskFileContent",
      "updateScheduledTaskFileContent",
      "updateScheduledTaskStatus",
      "updateScheduledTask",
      "createScheduledTask",
      "removeApprovedPermission",
      "clearChromePermissions",
    ],
    events: ["onScheduledTaskEvent"],
  },
  FileSystem: {
    invoke: [
      "browseFiles",
      "browseFolder",
      "browseFolders",
      "listDirectory",
      "listFilesInFolder",
      "readLocalFile",
      "writeLocalFile",
      "writeFileDownload",
      "writeFileDownloadAndOpen",
      "openLocalFile",
      "showInFolder",
      "whichApplication",
      "getSystemPath",
      "getLocalFileThumbnail",
      "promoteScratchpadFile",
      "savePastedFile",
      "exportLocalFileToGoogleDrive",
    ],
  },
  Resources: {
    invoke: ["fetchMentionOptions", "handleMentionSelect", "listProjectFiles", "searchFileContents", "setFocusedCwd", "setFindInPageClaimed"],
    events: ["findRequested"],
  },
  FindInPageProvider: {
    invoke: ["reportFindResult", "setProviderActive"],
    events: ["findRequest", "findClear"],
  },
  Toast: {
    events: ["showToast"],
  },
  Navigation: {
    events: ["navigate"],
  },
  DeepLink: {
    events: ["handleDeepLink"],
  },
  MenuEvents: {
    events: ["closeWindow", "openFile"],
  },
  QuickEntry: {
    invoke: ["setRecentChats"],
    events: ["onQuickEntrySubmit"],
  },
  Account: {
    invoke: ["setAccountDetails"],
  },
  Auth: {
    invoke: ["doAuthInBrowser"],
  },
  AutoUpdater: {
    invoke: ["checkForUpdates", "restartToUpdate", "restartToUpdateWhenIdle", "cancelPendingRestart", "getRunningLocalSessionCount", "updaterState_$store$_getState"],
    sync: ["updaterState_$store$_getStateSync"],
    events: ["updaterState_$store$_update"],
  },
  DesktopNotifications: {
    invoke: ["getAuthorizationStatus", "requestAuthorization", "openNotificationSettings", "showNotification"],
    events: ["onNotificationClicked"],
  },
  LocalSessionEnvironment: {
    invoke: ["get", "save"],
  },
  AgentModeFeedback: {
    invoke: ["openFeedbackWindow", "openFeedbackAndConfirmReinstall", "reportErrorToSlack"],
  },
  BuddyRemoteFeed: {
    invoke: ["sync"],
    events: ["permissionDecision"],
  },
  ChromeExtension: {
    invoke: ["isInstalled", "installExtension", "restartChrome"],
  },
  ClaudeCode: {
    invoke: ["checkGitAvailable", "getStatus", "prepare", "resolveLocalSettings"],
  },
  ClaudeVM: {
    invoke: [
      "download",
      "startVM",
      "getDownloadStatus",
      "getRunningStatus",
      "setForceDisableHostLoop",
      "setYukonSilverConfig",
      "deleteAndReinstall",
      "checkVirtualMachinePlatform",
      "enableVirtualMachinePlatform",
      "restartAfterVMPInstall",
      "apiReachability_$store$_getState",
    ],
    sync: ["isHostLoopModeEnabled", "isHostLoopDevOverrideActive", "apiReachability_$store$_getStateSync"],
    events: ["downloadProgress", "downloadStatusChanged", "runningStatusChanged", "startupError", "apiReachability_$store$_update"],
  },
  ComputerUseTcc: {
    invoke: ["getState", "getCurrentSessionGrants", "requestAccessibility", "requestScreenRecording", "openSystemSettings", "listInstalledApps", "revokeGrant"],
  },
  CoworkArtifacts: {
    invoke: [
      "getAllArtifacts",
      "getArtifactMetadata",
      "getArtifactIndexHtmlPath",
      "getArtifactThumbnail",
      "showArtifact",
      "hideArtifact",
      "reloadArtifactView",
      "parkAndCaptureArtifact",
      "importArtifact",
      "refreshImportedArtifact",
      "deleteArtifact",
      "setArtifactStarred",
      "restoreArtifactVersion",
      "setArtifactMcpTools",
      "isSharingEnabled",
      "shareArtifact",
      "unshareArtifact",
      "printArtifactToPdf",
    ],
    events: ["onArtifactsChanged"],
  },
  CoworkFilePreview: {
    invoke: ["isEnabled", "isVmReady", "show", "hide", "parkAndCapture"],
  },
  CoworkMemory: {
    invoke: ["listAccountMemories", "readAccountMemory", "writeAccountMemory", "deleteAccountMemory", "readGlobalMemory", "writeGlobalMemory", "resetMemories"],
  },
  CoworkRadar: {
    invoke: ["getCards", "getLastRun", "setCardStatus", "dismissCard", "adoptSession", "recordCardEngagement", "revealLastRunTranscript"],
    events: ["onRadarUpdated"],
  },
  CoworkSpaces: {
    invoke: [
      "getAllSpaces",
      "getSpace",
      "createSpace",
      "updateSpace",
      "deleteSpace",
      "addFolderToSpace",
      "removeFolderFromSpace",
      "addLinkToSpace",
      "removeLinkFromSpace",
      "addProjectToSpace",
      "removeProjectFromSpace",
      "classifySessions",
      "copyFilesToSpaceFolder",
      "createSpaceFolder",
      "listFolderContents",
      "getAutoMemoryDir",
      "readFileContents",
      "openFile",
      "setAutoDescription",
      "summarizeSpace",
    ],
    events: ["onSpaceEvent"],
  },
  CustomPlugins: {
    invoke: [
      "addMarketplace",
      "removeMarketplace",
      "refreshMarketplace",
      "listMarketplaces",
      "installPlugin",
      "updatePlugin",
      "uninstallPlugin",
      "listInstalledPlugins",
      "listAvailablePlugins",
      "getCachedCommands",
      "getInstallCounts",
      "listRemotePluginsPage",
      "checkPluginHasLocalChanges",
      "getAndClearMigrationIssues",
      "listLocalOrgPlugins",
      "installLocalOrgPlugin",
    ],
    events: ["installProgress"],
  },
  FloatingPenguinMini: {
    invoke: ["requestToggleMini", "requestSetMiniExpanded"],
    events: ["onMiniStateChanged"],
  },
  FramebufferPreview: {
    invoke: ["listSources", "attach", "detach", "requestFramePort", "sendKey", "sendPointer", "sendScroll", "setStreamHints"],
    events: ["openSourceRequested", "sessionFatal", "sessionResized"],
  },
  GrandPrix: {
    invoke: ["pair", "disconnect", "grandPrixStatus_$store$_getState"],
    sync: ["grandPrixStatus_$store$_getStateSync"],
    events: ["grandPrixStatus_$store$_update"],
  },
  Launch: {
    invoke: [
      "activeServers_$store$_getState",
      "getConfiguredServices",
      "getAutoVerify",
      "setAutoVerify",
      "deployPreview",
      "destroyPreview",
      "getPreviewUrl",
      "getLogs",
      "capturePreviewScreenshot",
      "clearPreviewViewport",
      "goBack",
      "goForward",
      "hidePreview",
      "showPreview",
      "loadHtmlPreview",
      "navigatePreview",
      "pickHtmlFile",
      "refreshPreview",
      "setPreviewColorScheme",
      "setPreviewViewport",
      "startFromConfig",
      "stopServer",
      "suggestDeployName",
      "toggleSelectionMode",
      "unpublishDeploy",
    ],
    sync: ["activeServers_$store$_getStateSync", "isAvailable"],
    events: ["activeServers_$store$_update", "deployEvent", "elementSelected", "previewSelectionShortcut", "previewUrlChanged"],
  },
  LocalPlugins: {
    invoke: [
      "getPlugins",
      "deletePlugin",
      "getDownloadedRemotePlugins",
      "getPluginCliStatus",
      "getPluginOAuthStatus",
      "getPluginShimOps",
      "listSkillFiles",
      "revokePluginOAuth",
      "setPluginEnabled",
      "setPluginEnvVars",
      "setPluginOAuthClient",
      "setPluginShimPermission",
      "startPluginOAuthFlow",
      "syncRemotePlugins",
      "uploadPlugin",
    ],
    events: ["onCliOpAlwaysAllowed"],
  },
  NestDev: {
    invoke: ["getState", "focus"],
  },
  OpenDocuments: {
    invoke: ["getOpenDocuments", "readOpenDocumentAsBase64"],
  },
  OrbitDeploys: {
    invoke: ["getAll", "setDeploy", "removeDeploy", "setPinned"],
  },
};
